name: godot-ci
on:
  push:
    branches: [ main ]
jobs:
  export-game:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Export game
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          gwith:
          godot_version: "4.6.2-stable"
          relative_project_path: ./
          cache: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: create release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
